name: MyFirstPlugin
version: '${project.version}'
main: net.najtex.myfirstplugin.MyFirstPlugin
api-version: 1.19
authors: [ Najtex ]
description: My first plugin for spigot

commands:
  heal:
    description: Heal to full health
  healthstats:
    description: Display your health
  createworld:
    description: Create a world
  deleteworld:
    description: Delete a world
  worldtp:
    description: Teleport to a world
  quickjoin:
    description: Join a random server
  createarena:
    description: Create an arena
